# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/wai-selecting-eval-tools" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
includes_dir: _external/wai-website-jekyll-templates/_includes
layouts_dir: _external/wai-website-jekyll-templates/_layouts
github:
  - url: 'wai-selecting-eval-tools'
exclude:
  - "_external"
# Build settings
markdown: kramdown

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Web Accessibility Initiative (WAI)"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Website of the World Wide Web Consortium’s Web Accessibility Initiative.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter:
  username: w3c_wai
author: w3c_wai
exclude:
  - "_external"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "w3c.json"

# Build settings
markdown: kramdown
kramwdown:
  toc_levels: 2..3
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
repository: w3c/wai-selecting-eval-tools

ytkey: AIzaSyCiZ9uToWu9jb7BTx47NtzCvmGGXKXp8nI

includes_dir: _external/wai-website-jekyll-templates/_includes
layouts_dir: _external/wai-website-jekyll-templates/_layouts

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-include-cache

